name: test

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: '^1.24.0'
        - run: go mod tidy
        - run: go mod download
        - run: protoc --go_out=. --go-grpc_out=. proto/file_service.proto
        - run: go get -u ./...
        - run: go test ./... -v
